name: Building mobile application

on:
  push:
    branches: [ master ]

jobs:
  export:
    name: Export assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - run: yarn install

      - run: expo export --public-url ${{ secrets.ASSETS_URL }}

      - uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.ASSETS_FTP_HOST }}
          user: ${{ secrets.ASSETS_FTP_USER }}
          password: ${{ secrets.ASSETS_FTP_PASSWORD }}
          localDir: dist
          remoteDir: ${{ secrets.ASSETS_FTP_REMOTE_DIR }}

  apk:
    name: Build .apk file
    runs-on: ubuntu-latest
    needs: export
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_FILES_PASSWORD: ${{ secrets.SECRET_FILES_PASSWORD }}

      - uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: ${{ runner.os }}-turtle

      - run: |
          yarn install
          npm install -g turtle-cli
          turtle build:android -o ./build.apk --keystore-path ./secrets/build.keystore --keystore-alias ${{ secrets.ANDROID_KEYSTORE_ALIAS }} --public-url ${{ secrets.ASSETS_URL }}/android-index.json -t apk
        env:
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}

      - name: Archive .apk build
        uses: actions/upload-artifact@v1
        with:
          name: build.apk
          path: ./build.apk

  ipa:
    name: Build .ipa file
    runs-on: macos-latest
    needs: export
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_FILES_PASSWORD: ${{ secrets.SECRET_FILES_PASSWORD }}

      - uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: ${{ runner.os }}-turtle

      - run: |
          yarn install
          npm install -g turtle-cli
          turtle build:ios -o build.ipa --team-id ${{ secrets.APPLE_TEAM_ID }} --dist-p12-path ./secrets/cert.p12 --provisioning-profile-path ./secrets/profile.mobileprovision --public-url ${{ secrets.ASSETS_URL }}/ios-index.json
        env:
          EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

      - name: Archive .ipa build
        uses: actions/upload-artifact@v1
        with:
          name: build.ipa
          path: ./build.ipa
